name: Update pinned, translate, build and deploy site

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 */3 * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Fetch pinned repos
        run: npm run fetch:pinned
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate language colors via Gemini
        run: npm run colors:update
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Generate pinned translations
        run: npm run translate:pinned
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Generate content translations
        run: npm run translate:content
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/assets/pinned.json src/locales
          git commit -m "chore: update pinned.json and translations" || echo "No changes"
          git push

      - name: Build site
        run: npm run build-only

      - name: Create 404.html fallback
        run: cp dist/index.html dist/404.html

      - name: Wait until no Pages deployment is in progress
        run: |
          echo "Waiting for any ongoing Pages deployment to finish..."
          while true; do
            deployment_id=$(gh api repos/${GITHUB_REPOSITORY}/pages/deployment --jq '.[0].id' 2>/dev/null || echo "")
            if [ -z "$deployment_id" ]; then
              echo "No deployment found. Proceeding..."
              break
            fi
            status=$(gh api repos/${GITHUB_REPOSITORY}/pages/deployment/$deployment_id --jq '.status')
            if [[ "$status" == "in_progress" || "$status" == "building" ]]; then
              echo "Deployment $deployment_id status: $status. Waiting 15s..."
              sleep 15
            else
              echo "Deployment $deployment_id completed. Proceeding..."
              break
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
