name: Deploy Vue.js site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Fetch pinned
      - name: Fetch pinned
        run: npm run fetch:pinned

      # Update colors
      - name: Update colors
        run: npm run colors:update

      # Translate pinned
      - name: Translate pinned
        run: npm run translate:pinned

      # Translate content
      - name: Translate content
        run: npm run translate:content

      # Build Vue.js site
      - name: Build Vue.js site
        run: npm run build

      # Deploy to main branch (GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main       # main-haara julkaisuun
          publish_dir: ./dist
          keep_files: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
