name: Translate content

on:
  workflow_run:
    workflows: ["Translate pinned"]
    types:
      - completed

permissions:
  contents: write

jobs:
  translate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate content translations
        run: npm run translate:content
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit content translations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/locales
          git commit -m "chore: update content translations" || echo "No changes"
          git push
